site_name: Wind Tempos Documentation
theme:
  name: shadcn
  show_stargazers: false
  icon: img/favicon.ico
  topbar_sections: true
  show_datetime: true
markdown_extensions:
  - admonition
  - codehilite
  - shadcn.extensions.hover_card
site_url: https://docs.windtempos.com/
repo_url: https://github.com/Bittorn/WindTempos-Docs
nav:
  - Home: index.md
  - Shaymin Cobblemon:
      - Server Rules: shaymin/rules.md
      - Mods and Packs: shaymin/content.md
      - Custom Content: shaymin/custom.md
      - Modpack License: shaymin/license.md

      - Shaymin League:
          - Competitive Rules: shaymin/league_rules.md
